extends Node

const ITEM_ENERGY_MAP = {
	"cabbage": 0.4,
	"beans": 0.2
}

const REST_ENERGY = 0.1
const REST_RADIATION = -0.05

const CROP_MIN_HEALTH = 0.66
const CROP_PLANTING_MIN_HEALTH = 0.75

const WATERING_INTERVAL = 0.3
const DECAY_NITROGEN = 0.2
const DECAY_CHANCE = 0.05
const WEED_SPAWN_CHANCE = 0.02

const ACTION_FERTILIZE_ENERGY = -0.05
const ACTION_FERTILIZE_NITROGEN_CHANGE = 0.01
const ACTION_FERTILIZE_NITROGEN_RADIUS = 5

const ACTION_PLANT_ENERGY = -0.1
const ACTION_PLANT_RADIATION = 0.01

const ACTION_WATER_ENERGY = -0.02
const ACTION_WATER_CONSUMPTION = -0.1
const ACTION_WATER_HYDRATION = 0.1
const ACTION_WATER_RADIATION = 0.005

const ACTION_HARVEST_ENERGY = -0.05
